class LuckySvgSprite::Generator
  def initialize(@path : String)
  end

  def icons
    Dir.glob("#{@path}/*.svg").sort
  end

  def concatenate(format : Format)
    icons.map do |icon|
      Converter.from_file(icon, format)
    end.join("\n").strip
  end

  def sprite_name
    @path.strip
      .gsub(/\/$/, "")
      .split('/').last
      .underscore
      .gsub(/[\.\-\s]+/, "_")
      .gsub(/^_|_$/, "")
      .camelcase
      .gsub(/^\d+/, "")
  end

  def generate(format : Format)
    format.indent = 4
    <<-CODE
    # DO NOT EDIT! This file is generated by the lucky_svg_sprite shard.
    # More information available here:
    # https://github.com/tilishop/lucky_svg_sprite.cr#generating-sprites
    class SvgSprite::#{sprite_name} < BaseSvgSprite
      def render_icons : IO
        #{concatenate(format)}
      end

      class Icon < BaseSvgIcon
      end
    end
    CODE
  end
end
