require "spec"
require "../src/lucky_svg_sprite/mixins/icon.cr"
require "../src/lucky_svg_sprite/mixins/set.cr"
require "../src/lucky_svg_sprite/generator.cr"
require "../src/lucky_svg_sprite/version.cr"
